### ISSUE TITLE
Fix JetBrains IDEs 

### ISSUE THREAD

**Issue by jakeisnt** [jakeisnt/nix-cfg#81]
Android Studio is really not fun to work with when the popups and suggestions don't work at all
https://github.com/swaywm/sway/issues/3007
https://github.com/swaywm/wlroots/issues/2604

**Comment by tsdh** [comment]
@jakeisnt This issue is solved for me using the current git master branches of sway and wlroots thanks to the latest PRs of @BrassyPanache. The relevant PRs are #5948 and https://github.com/swaywm/wlroots/pull/2605.  You might want to test using the current development versions of sway and wlroots.

**Comment by jakeisnt** [comment]
This has been resolved
